CREATE DATABASE WechatDemo;

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    OpenId NVARCHAR(100) NOT NULL UNIQUE,
    Username NVARCHAR(100) NOT NULL,
    Role NVARCHAR(20) NOT NULL DEFAULT 'User',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);